# Generated by Django 4.0.4 on 2022-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgd_binimg', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CaptureImage',
                'ordering': ['-id'],
            },
        ),
    ]
