# Generated by Django 4.0.4 on 2022-07-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotestapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captureimage',
            old_name='imgd_binimg',
            new_name='img',
        ),
    ]
