# Generated by Django 4.0.4 on 2022-07-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotestapp', '0004_alter_captureimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureimage',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
