# Generated by Django 4.0.4 on 2022-07-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotestapp', '0005_alter_captureimage_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captureimage',
            options={},
        ),
        migrations.RenameField(
            model_name='captureimage',
            old_name='id',
            new_name='img_id',
        ),
    ]
