# Generated by Django 4.0.4 on 2022-07-04 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangotestapp', '0006_alter_captureimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
